name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3'

      - name: Generate contents
        run: |
          hugo --minify
          sudo apt-get -y install python3
          python3 main.py
          mkdir public/data/nginx
          mv block-public-proxy.conf public/data/nginx/
          mv block-bulletproof.conf public/data/nginx/

      - uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: lance-network
          directory: ./public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}